version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: InvoiceApi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    ports:
      - "5466:5466"